'use client';
import { useEffect, useRef } from 'react';
import { X, MapPin, Phone, Globe, Flag, ArrowUpRight, Gift, Map } from 'lucide-react';
import type { GolfCourse } from '@/lib/types';
export default function GolfCourseSheet({ course, onClose }: { course: GolfCourse | null; onClose: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { if (course) dialog.current?.showModal(); else dialog.current?.close(); }, [course]);
  return <dialog ref={dialog} className="course-dialog" onCancel={onClose} onClick={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="sheet-content">{course && <><div className="sheet-handle"/><button className="sheet-close" onClick={onClose} aria-label="골프장 상세 닫기"><X size={22}/></button><span className="eyebrow">COURSE DETAILS</span><h2>{course.name}</h2><span className={course.plkPartner ? 'partner-badge' : 'regular-badge'}>{course.plkPartner ? '✦ PLK 제휴 골프장' : '일반 골프장'}</span><p className="detail-line"><MapPin size={18}/>{course.address}</p><p className="detail-line"><Flag size={18}/>{course.holes ? `${course.holes}홀` : '홀 정보 미등록'}</p>{course.partnerNote && <p className="detail-line"><Gift size={18}/>{course.partnerNote}</p>}<div className="detail-actions">{course.phone ? <a href={`tel:${course.phone}`}><Phone size={19}/>{course.phone}</a> : <span><Phone size={19}/>전화번호 미등록</span>}{course.homepage ? <a href={course.homepage} target="_blank" rel="noopener noreferrer"><Globe size={19}/>홈페이지 <ArrowUpRight size={16}/></a> : <span><Globe size={19}/>홈페이지 미등록</span>}{course.kakaoPlaceUrl && <a className="wide" href={course.kakaoPlaceUrl} target="_blank" rel="noopener noreferrer"><Map size={19}/>카카오맵에서 보기 <ArrowUpRight size={16}/></a>}</div><p className="sample-note">정보 출처: PLK · 카카오맵. 운영 정보는 골프장에 확인해 주세요.</p><button className="primary-button" onClick={onClose}>지도 계속 둘러보기</button></>}</div></dialog>;
}
